{{- if .Values.rabbitmq.createUser }}
apiVersion: v1
kind: Secret
metadata:  
  name: {{ include "helsenorge-application.rabbitmqUserSecret" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  username: {{ include "helsenorge-application.rabbitmqUser" . | b64enc }}
  # try to get the old password
  # keep in mind, that a dry-run only returns an empty map 
  {{- $old_password := lookup "v1" "Secret" .Release.Namespace ( include "helsenorge-application.rabbitmqUserSecret" . ) }}
  # check, if a secret is already set
  {{- if or (not $old_password) (not $old_password.data) }}
  # if not set, then generate a new password
  password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  # if set, then use the old value
  password: {{ index $old_password.data "password" }}
  {{ end }}
{{- end }}