{{- if .Values.rabbitmq.createUser }}
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  rabbitmqClusterReference:
    name: {{ .Values.rabbitmq.clusterName }}
  importCredentialsSecret:
    name: {{ include "helsenorge-application.rabbitmqUserSecret" . }}
{{- end }}