apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helsenorge-application.fullname" . }}
  labels:
    {{- include "helsenorge-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      {{- include "helsenorge-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helsenorge-application.labels" . | nindent 8 }}
      annotations: 
        splunk.com/sourcetype: {{ .Values.splunk.sourceType }}
    spec:
      serviceAccountName: {{ include "helsenorge-application.serviceAccountName" . }}
      containers:
        - name: {{ include "helsenorge-application.fullname" .  }} 
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "helsenorge-application.image" . }} 
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command: [{{ .Values.image.command }}]
          args: 
          {{- range .Values.image.args }}
            - {{ . }}
          {{- end }}
          envFrom:
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .Values.aspnetCoreEnvironment | quote }}
          - name: HN_InternalMessagingSettings__Credentials__Username
            value: {{ .Values.rabbitmq.user | quote }}
          - name: HN_InternalMessagingSettings__Credentials__Password
            value: {{ .Values.rabbitmq.password | quote }}
          - name: HN_EhelseSecurityTokenServiceSettings__ClientId
            value: {{ .Values.clientId | quote }}
          - name: HN_EhelseSecurityTokenServiceSettings__ClientSecret
            value: {{ .Values.clientSecret | quote }}
          - name: HN_LoggingConfiguration__Area
            value: {{ include "logging.area" . | quote }}
          {{- range $key, $val := .Values.extraEnvVars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.global.extraEnvVars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
           {{- if or .Values.extraEnvVarsCM .Values.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.extraEnvVarsCM }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.extraEnvVarsCM "context" $) | nindent 12 }} 
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.extraEnvVarsSecret "context" $) | nindent 12 }}
            {{- end }}
          {{- end }}
          volumeMounts:
          {{- if .Values.debug.enabled }}
          - name: debug-environment
            mountPath: {{ .Values.debug.configShare }}
            readOnly: true
          {{- end }}
          {{- if .Values.tokenValidation.enabled }}
          - name: helsenorge-sikkerhet-public
            mountPath: {{.Values.tokenValidation.mountPath }}
            readOnly: true
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.tokenValidation.enabled }}
      - name: helsenorge-sikkerhet-public
        secret: 
          secretName: {{ .Values.tokenValidation.secretName}}
      {{- end }}
      {{- if .Values.debug.enabled }}
      - name: debug-environment
        configMap: 
          name: {{ .Values.debug.debugConfigMap }}
      {{- end }}
