{{- if  .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullName" . }}
  labels:
    {{- include "helsenorge-application.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  rules:
  - host: {{ include "helsenorge-application.hostname" . }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ include "application.fullName" . }}
            port:
              number: {{ .Values.service.port | default 80 }}
{{- end}}