apiVersion: v1
kind: ConfigMap 
metadata:
  name: {{ include "configurationFileShare.ConfigMapName" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  {{ printf "%s%s" (include "configPrefix" .) "ConfigurationFileShare__Share" }}: {{ .Values.configurationFileShare.share | quote }}

