apiVersion: v2
name: helsenorge-job
description: Helm chart for installere en helsenorge-job på kuberntes. En job beskriver en engangskjøring av en eller flere pod'er ved deploy. Passer for kjøring databasemigreringer eller console applikasjoner.

type: application
maintainers: 
  - name: Plattform
  
version: 0.0.21

dependencies:
- name: helsenorge-common
  version: "~0.0.1"
  repository: "https://helsenorge.github.io/helm-charts/"
  #repository: "file://../helsenorge-common"

