
# -- Overrider navn på chart. Beholder release-navnet
nameOverride: ""
# -- Overrider navn på chart. 
fullnameOverride: ""
# -- Hentes fra Chart.Maintainers[0].name (Chart.yaml) - Kan ovverides ved behov, også globalt.
teamOvveride: ""
# -- Beskriver imaget til applikasjonen
# @default -- Se verdier under
image:
  # -- Fra hvilket container registry skal imaget hentes. 
  registry: helsenorge.azurecr.io
  # -- Navn på imaget som skal deployes. Hvis ikke definert, settes til det samme som navnet på applikasjonen. TODO: gjøre det mulig å overstyre repository
  repository: ""
  # -- Kubernetes image pull-policy.
  # Les mer om image pull policy [her](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy).
  pullPolicy: IfNotPresent
  # -- tag identifiserer versjonen på imaget som skal deployes 
  tag: ""
# -- Ovveride default container command - defaulter til "dotnet" - Les mer om Command and Arguments for kontainere [her](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/).
command: 
# -- Ovveride default container args - Les mer om Command and Arguments for kontainere [her](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/).
args: 

# -- Labels som legges på alle objeckter som deployes
commonLabels:
# -- Annoteringer som legges på alle objeckter som deployes 
commonAnnotations:

# -- Restart policien til en pod. Defaulter til Never for en engangsjobb. Mulige verdier er Always, OnFailure, and Never. Les mer [her](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy).
restartPolicy: Never
# -- Antall forsøk jobben får før den markeres som feilet
backoffLimit: 1

# -- Environment variabler som tilgjengeliggjøres podden - Brukes for å overstyre config-settings
# Skrives på formen key: value
# Husk å bruke prefix HN_ for at environment-variabelen skal leses inn av config-systemet
# HN_ConfigurationSettings_Connectionstring: "Server=sql;Database=databasename;User Id=user;Password=password;"
# Kan også overstyres globalt:
# global:
#   extraEnvVars:
#     HN_ConfigurationSettings_Connectionstring: "Server=sql;Database=databasename;User Id=user;Password=password;"
extraEnvVars:
# Navn på eksisterende config-map som inneholder extra env-vars - må skrives på formen for en gyldig configMapRef og config-map må eksistere fra før
extraEnvVarsCM: 
  - configMapRef:
      name: "felles-config"
# Navn på eksisterende secret som inneholder extra env-vars - må skrives på formen for en gyldig secretRef og secret må eksistere fra før
extraEnvVarsSecret: 
  - secretRef:
      name: "felles-config"
# Definisjon på extra volume som skal tilgjengeliggjøres til deploymenten
extraVolumes:
# Definisjon på extra volume mount som skal mountes til podden
extraVolumeMounts:
# -- Kubernetes service-konto. Les mer [her](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/).
# Navn settes til det samme som applikasjon.
serviceAccount:
  # -- Spesifiserer om en service-konto skal opprettes.
  create: true
  # -- Legger på egne image pull secrets på service accounten
  imagePullSecrets: 
    - helsenorge-pull-secret



