
# -- Overrider navn på chart. Beholder release-navnet
nameOverride: ""
# -- Overrider navn på chart. 
fullnameOverride: ""
# -- Hentes fra Chart.Maintainers[0].name (Chart.yaml) - Kan ovverides ved behov, også globalt.
teamOvveride: ""
# -- Image referanse: registry/repository:tag
image: 
# -- Pull-policy satt på imaget
imagePullPolicy: IfNotPresent
# -- Ovveride default container command - defaulter til "dotnet" - Les mer om Command and Arguments for kontainere [her](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/).
command: 
# -- Ovveride default container args - Les mer om Command and Arguments for kontainere [her](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/).
args: 
# -- Labels som legges på alle objeckter som deployes
commonLabels:
# -- Annoteringer som legges på alle objeckter som deployes 
commonAnnotations:
# -- Restart policien til en pod. Defaulter til Never for en engangsjobb. Mulige verdier er Always, OnFailure, and Never. Les mer [her](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy).
restartPolicy: Never
# -- Antall forsøk jobben får før den markeres som feilet
backoffLimit: 1
# -- Map av environment variabler som tilgjengeliggjøres for podden. Se [her](env-eksempler) for eksempler.
extraEnvVars: {}
# -- Liste over eksisterende config-maps der innholdet lastes inn i podden som envVars. Se [her](#envfrom-configmap-eksempler) for eksempler. 
extraEnvVarsCM: []
# -- Liste over eksisterende secrets der innholdet lastes inn i podden som envVars. Se [her](#envfrom-secret-eksempler) for eksempler.
extraEnvVarsSecret: []
# -- Liste over extra volumes som skal tilgjengeliggjøres til deploymenten. Se [her](#volume-og-volumemount-eksempler) for eksempler.
extraVolumes: []
# -- Liste over extra volume mounts som skal mountes til podden. Se [her](#volume-og-volumemount-eksempler) for eksempler.
extraVolumeMounts: []
# -- Kubernetes service-konto. Les mer [her](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/).
# Navn settes til det samme som applikasjon.
serviceAccount:
  # -- Spesifiserer om en service-konto skal opprettes.
  create: true
  # -- Legger på egne image pull secrets på service accounten. Gjør det mulig for pods som kjører under denne service-accounten å få tilgang til private registry
  imagePullSecrets: 
    - helsenorge-pull-secret
# -- Gir pod'en tilgang til felles-config allerede tilgjengeligjort i miljoet. Dette er typisk config som kreves av felles-pakkene.
useSharedConfig: true
# -- Legger inn hostfil innslag i pod'ens /etc/host. Se [her](#hostalias-eksempler) for eksempler.
hostAliases: []




