apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  template:
    spec:
      containers:
      - name: {{ include "common.fullname" .  }} 
        image:  {{ include "common.image" . }}
        command:
        {{- if .Values.command }}
        {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
        {{- else }}
        - dotnet
        {{- end }}
        {{- if .Values.args }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
        {{- end }}  
        env:
          {{- range $key, $val := .Values.extraEnvVars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.global.extraEnvVars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
  backoffLimit: {{ .Values.backoffLimit }}
  