apiVersion: v2
name: helsenorge-common
description: Chart med felles helm-metoder for utvikling av helsenorge application-charts.

type: library

maintainers: 
  - name: Team Plattform
    email: "utv-hn-plattform@norskhelsenett.slack.com"
    url: "https://www.nhn.no/"
version: 0.0.5