
area:
  name: '#{k8s.area.name}'
  team: '#{k8s.area.team}'

image:
  tag: '#{Octopus.Action.Package[docker-container].PackageVersion}'

envVariables:
  ASPNETCORE_ENVIRONMENT: '#{Helsenorge.AspnetCore_Environment}'
  
TokenValidationSettings: 
  SigningCertificate: '#{SikkerSone.Sertifikat.Signering.Thumbprint}'

InternalMessagingSettings:
  RootAddress: '#{InternalMessagingSettings:RootAddress}'
  VirtualHost: '#{InternalMessagingSettings:VirtualHost}'
  ConfigurationCredentials:
    Username: '#{InternalMessagingSettings:ConfigurationCredentials:Username}'
    Password: '#{InternalMessagingSettings:ConfigurationCredentials:Password}'
  Credentials:
    Username: '#{InternalMessagingSettings:Credentials:Password}'
    Password: '#{InternalMessagingSettings:Credentials:Password}'

DistributedPersistentCache:
  Configuration: '#{DistributedPersistentCache:Configuration}'
  CacheKeyPrefix: '#{DistributedInMemoryCache:CacheKeyPrefix}'
  AreaEncryptionKey: '#{DistributedInMemoryCache:AreaEncryptionKey}'
  GlobalEncryptionKey: '#{DistributedInMemoryCache:GlobalEncryptionKey}'

featureEnvironment:
  isFeatureEnvironment: #{if Octopus.Environment.Name == "FARM1-FEATURE"}true#{/if}
  