# -- Overrider navn på chart. Beholder release-navnet
nameOverride: ""
# -- Overrider navn på chart. 
fullnameOverride: ""

# -- Ansvarlig team for losningsomraade - eks "Plattform". 
team: ""

# -- ClientId for applikasjonen
clientId: ""
# -- Tilhørende secret
clientSecret: ""

# -- setter ASPNETCORE_ENVIRONMENT environment-variabelen i pod
aspnetCoreEnvironment: "k8s"

# -- Messagings settings - Blir tilgjengeliggjort som environment-variabler i pod
rabbitmq:
  # -- Bruker
  user: ""
  # -- Passord
  password: ""

# -- Logging
logging:
  # Area settes automatisk til samme som Release.Name. Denne verdien kan ovverides her.
  areaOvveride: ""

# -- Splunk
splunk:
  # -- Setter SourceType på loggene i splunk
  sourceType: kube:Helsenorge

# -- Dns-sonen til miljøet.
dnsZone: "aks-helsenorge.utvikling"
# -- Beskriver imaget til applikasjonen
# @default -- Se verdier under
image:
  # -- Fra hvilket container registry skal imaget hentes. 
  registry: helsenorge.azurecr.io
  # -- Navn på imaget som skal deployes. Hvis ikke definert, settes til det samme som navnet på applikasjonen. TODO: gjøre det mulig å overstyre repository
  repository: ""
  # -- Kubernetes image pull-policy.
  # Les mer om image pull policy [her](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy).
  pullPolicy: IfNotPresent
  # -- Kommandoen som skal kjøre inne i imaget ved oppstart. 
  # Dette kan være pathen til et bash-script, kjoring av en executable eller annet. Bestemmes av hvordan container-imaget er bygget.
  # Ler mer om entrypoint [her](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/).
  command: "/app/container-startup.sh" 
  # -- tag identifiserer versjonen på imaget som skal deployes 
  tag: ""
  # -- Argumenter til commanden. Beskrives som et array.
  args: []
# -- Referanse til secret som inneholder nøkler for å få kontakt med private container registry (hvis dette er i bruk)
imagePullSecrets: []
# -- Antall containere som kjører apiet. Disse lastbalanseres automatisk, men flere containere krever mer ressurser av clusteret. Bør overstyrers i høyere miljøer.
replicaCount: 1
livenessProbe:
  # -- [Liveness probe](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#types-of-probe) indikerer om containeren kjører ved å gjøre et http kall mot gitt path.
  path: "/api/ping"
readinessProbe:
   # -- [Readiness probe](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#types-of-probe) indikerer om containeren er klar for å motta requests ved å gjøre et http kall mot gitt path
  path: "/health"
# -- Kubernetes service-konto for losningsomraade. Les mer [her](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/).
# Navn settes til det samme som applikasjon.
serviceAccount:
  # -- Spesifiserer om en service-konto skal opprettes.
  create: true
  # -- Spesifikke annoteringer som skal legges til servicekontoen (todo).
  annotations: {}
# -- Servicen som eksponerer apiet ut i klusteret.
# @default -- Se verdier under
service:  
    # -- Type service.
    # Les mer [her](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).
    type: "ClusterIP" 
    # -- Port servicen eksponerer apiet på ut i clusteret.
    port: 80 
# -- Beskriver hvordan komponenten skal eksponeres ut av clustert, slik at komponenten kan konsumeres av ressurser utenfor clusteret. 
# Les mer [her](https://kubernetes.io/docs/concepts/services-networking/ingress/).
# @default -- Se verdier under
ingress: 
  # -- Bestemmer om en ingress skal opprettes eller ikke, false betyr at ingen ingress opprettes og komponenten kan ikke nås utenfra clusteret.
  create: true
  # -- Bestemmer hvilket hostname ingress skal lytte på. Eks configuration-internalapi-mas01.helsenorge.utvikling.
  # Trenger ikke overstyres med mindre man skal teste noe spesielt
  # @default -- kalkuleres basert på apinavn og miljo
  hostname: ""
  className: "nginx"
# -- Beskriver hvor mye ressurser en pod som kjører koden skal få tilgang til.
# Les mer om konseptene [her](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits).
# @default -- Se verdier under
resources:
  # -- Hvor mye ressurser er poden begrenset til.
  # @default -- Se verdier under
  limits:
    # -- [Limits and requests for CPU resources are measured in cpu units. One cpu, in Kubernetes, is equivalent to 1 vCPU/Core for cloud providers and 1 hyperthread on bare-metal Intel processors](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu).
    cpu: 200m
    # -- [Limits and requests for memory are measured in bytes.](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory).
    memory: 128Mi
  # -- Hvor mye ressurser poden minimum trenger.
  # @default -- Se verdier under
  requests:
    # -- Samme som under resources.limits.
    cpu: 100m
    # -- Samme som under resources.limits.
    memory: 128Mi

# -- Environment variabler som tilgjengeliggjøres podden - Brukes for å overstyre config-settings
# Skrives på formen key: value
# Husk å bruke prefix HN_ for at environment-variabelen skal leses inn av config-systemet
# Eks: 
# HN_ConfigurationSettings_Connectionstring: "Server=sql;Database=databaename;User Id=user;Password=password;"
extraEnvVars:
# Navn på eksisterende config-map som inneholder extra env-vars - må skrives på formen for en gyldig configMapRef og config-map må eksistere fra før
extraEnvVarsCM: 
  - configMapRef:
      name: "felles-config"
# Navn på eksisterende secret som inneholder extra env-vars - må skrives på formen for en gyldig secretRef og secret må eksistere fra før
extraEnvVarsSecret: 
  - secretRef:
      name: "felles-config"

# Definisjon på extra volume som skal tilgjengeliggjøres til deploymenten
extraVolumes:
  - name: helsenorge-sikkerhet-public
    secret: 
      secretName: certificate.helsenorge-sikkerhet.public

# Definisjon på extra volume mount som skal mountes til podden
extraVolumeMounts:
  - name: helsenorge-sikkerhet-public
    mountPath: /certificates
    readOnly: true

  # -- debugmodus
debug:  
  # -- skrur på debug-modus i miljøet. Krever at debug.dll config-map er tilgjengelig i miljøet.
  enabled: false
  # -- path i pod der debug-dll blir tilgjengeligjort
  configShare: /config-share/
  # -- navn på config-map som inneholder debug-dll. Denne må eksistere i namespace fra før
  debugConfigMap: debug-environment

