
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "internalMessaging.Secret" . }}
  labels:
    {{- include "helsenorge-application.labels" . | nindent 4 }}
data:
  {{ printf "%s%s" (include "configPrefix" .)  "InternalMessagingSettings__Credentials__Password"}}: {{ default "" .Values.internalMessaging.password | b64enc | quote}}
  