apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      containers:
      - name: {{ include "common.fullname" .  }} 
        image:  {{ include "common.image" . }}
        command:
        {{- if .Values.command }}
        {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
        {{- else }}
        - dotnet
        {{- end }}
        {{- if .Values.args }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
        {{- end }}  
        env:
          {{- range $key, $val := merge (default dict .Values.extraEnvVars) (default dict .Values.global.extraEnvVars)  }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
        envFrom:
          {{- if .Values.useSharedConfig }}
          - configMapRef:
              name: felles-config
          - secretRef:
              name: felles-config
          {{- end }}
          {{- if or .Values.extraEnvVarsCM .Values.extraEnvVarsSecret }} 
            {{- if .Values.extraEnvVarsCM }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.extraEnvVarsCM "context" $) | nindent 10 }} 
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.extraEnvVarsSecret "context" $) | nindent 10 }}
            {{- end }}
          {{- end }}
        {{- if .Values.extraVolumeMounts }}
        volumeMounts:
          {{- include "common.tplvalues.render" ( dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }} 
        {{- end }} 
      restartPolicy: {{ .Values.restartPolicy }}
    {{- if .Values.extraVolumes }}
    volumes:
      {{- include "common.tplvalues.render" ( dict "value" .Values.extraVolumes "context" $) | nindent 10 }}
    {{- end }} 
  backoffLimit: {{ .Values.backoffLimit }}
  