configPrefix: HN_

# -- Fellesconfig for fellesloggen
# @default -- Se verdier under
fellesloggClientSettings:
  # -- Uri til felleslogg-endepunkt
  endpointUri: http://felleslogg-internalapi

# -- Fellesconfig for STS
# @default -- Se verdier under
ehelseSecurityTokenServiceSettings: 
  # -- Uri til tokenservice-endepunkt
  endpointUrl: http://sts-tokenservice
  timeout: "00:05:00"
  connectionTimeout: 00:05:00
  # -- ClientId for løsningsområde
  clientId: 
  # -- ClientSecret for løsningsområde
  clientSecret:

# -- Fellesconfig for Ressursfiler (SOT)
# @default -- Se verdier under
sotApiClient: 
  # -- Uri til SOT-endepunkt
  endpointUri: http://sot-internalapi
  requestTimeout: 00:00:05
  connectionTimeout: 00:05:00

# -- Fellesconfig for Tokenvalidering
# @default -- Se verdier under
tokenValidationSettings: 
  # -- Thumbprint til valideringssertifikat
  signingCertificate: F46ECB29F8B9994D2286B073C1CEA6A52BB746FC
  # -- Hashingsecret
  tokenHashingSecret: 

# -- Fellesconfig for intern meldingsutveksling
# @default -- Se verdier under
internalMessagingSettings:
  # -- Adresse til rabbitmq instans
  rootAddress: rabbitmq://rabbitmq:5671
  # -- Navn på rabbitmq virtual host
  virtualHost: internal.messaging.helsenorge.no
  # -- Navn på rabbitmq client
  name: Configuration
  configurationCredentials:
    # -- Navn på rabbitmq bruker med rettigheter til utføre konfigurasjoner i rabbitmq
    username: rmq_config_user
    # -- Passord til rabbitmq bruker med rettigheter til utføre konfigurasjoner i rabbitmq
    password: rO9ZbR1w 
  credentials:
    # -- Navn på clientens rabbitmq-bruker
    username: 
    # -- Passord til clientens rabbitmq-bruker
    password: 
  # -- Skal ssl brukes i kommunikasjonen mot rabbitmq
  useSsl: true
  # -- Skal meldinger krypteres
  encryptMessages: false
  # -- Krypteringsnøkkel for krypterte meldinger
  symmetricKey: 

# -- Fellesconfig for intern redis-cache
# @default -- Se verdier under
distributedPersistentCache:
  # --  Navn på områded til clienten.
  areaName: 
  # --  Redis-config
  configuration: redis-persistence-master:6379
  # --  Skal cache prefixes. Kun relevant der flere miljøer deler redis-instans.
  cacheKeyPrefix: ""
  # --  Krypteringsnøkkel for området.
  areaEncryptionKey: 
  # --  Global krypteringsnøkkel.
  globalEncryptionKey: 


